services:
  backend:
    extends:
      file: common.yaml
      service: backend
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./backend:/app/backend
    command: /app/backend/entrypoint.dev.sh
    # command: ["python3", "-m", "debugpy", "--listen",
    #           "0.0.0.0:5678", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - ./backend/.env.dev

  db:
    extends:
      file: common.yaml
      service: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d copygram-dev"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - copygram-dev-dbdata:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.dev

  redis:
    extends:
      file: common.yaml
      service: redis
    volumes:
      - copygram-dev-redisdata:/data

  celery:
    extends:
      file: common.yaml
      service: celery
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env.dev

  celerybeat:
    extends:
      file: common.yaml
      service: celerybeat
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env.dev

  nginx:
    extends:
      file: common.yaml
      service: nginx
    volumes:
      - copygram-dev-staticdata:/app/staticfiles

  # elasticsearch:
  #   extends:
  #     file: common.yaml
  #     service: elasticsearch
  #   volumes:
  #     - copygram-dev-esdata:/usr/share/elasticsearch/data

  # rabbit:
  #   extends:
  #     file: common.yaml
  #     service: rabbit


networks:
  copygram-network:
    driver: bridge
    name: copygram-network


volumes:
  copygram-dev-dbdata:
    driver: local
    name: copygram-dev-dbdata
  copygram-dev-staticdata:
    driver: local
    name: copygram-dev-staticdata
  copygram-dev-redisdata:
    driver: local
    name: copygram-dev-redisdata
  # copygram-dev-esdata:
  #   driver: local
  #   name: copygram-dev-esdata
