# Generated by Django 5.1.3 on 2024-11-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='roomchat',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='roomchat',
            old_name='created',
            new_name='created_at',
        ),
    ]
