# Generated by Django 5.1.3 on 2025-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_privatechat_first_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(default='static/img/group.png', upload_to='rooms/%Y/%m/%d/'),
        ),
    ]
