# Generated by Django 5.1.3 on 2025-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_groupchat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(default='users/static/img/group.png', upload_to='rooms/%Y/%m/%d/'),
        ),
    ]
