# Generated by Django 5.1.3 on 2025-01-11 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_groupchat_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(upload_to='rooms/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
