# Generated by Django 5.1.3 on 2025-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_groupchat_image_alter_groupchat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, upload_to='rooms/%Y/%m/%d/'),
        ),
    ]
