# Generated by Django 4.2.13 on 2024-11-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('users', '0004_alter_user_gender_alter_userprivacy_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentPreferences',
            new_name='ContentPreference',
        ),
    ]
