# Generated by Django 4.2.13 on 2024-11-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_uninterestingpost_delete_unintrestingpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UninterestingPost',
        ),
    ]
