# Generated by Django 5.1.3 on 2024-11-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userdayactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='unread',
        ),
    ]
