# Generated by Django 5.1.3 on 2025-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_action_options_alter_referral_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User activities'},
        ),
        migrations.AlterModelOptions(
            name='userdayactivity',
            options={'verbose_name_plural': 'User day activities'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/img/user.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
