# Generated by Django 5.1.3 on 2025-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/static/img/user.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
